-- =====================================================
-- BASE DE DATOS: RESTAURANTE
-- PostgreSQL
-- =====================================================

CREATE DATABASE restaurante;

-- Conectarse a la base de datos antes de ejecutar el resto
-- \c restaurante

-- =====================================================
-- TABLAS MAESTRAS
-- =====================================================

CREATE TABLE DB_Categoria (
    DB_Categoria_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codCategoria VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE DB_Proveedor (
    DB_Proveedor_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codProveedor VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    telefono VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    direccion VARCHAR(255) NOT NULL
);

CREATE TABLE DB_Rol (
    DB_Rol_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codRol VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE DB_Permiso (
    DB_Permiso_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codPermiso VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE DB_Mesa (
    DB_Mesa_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codMesa VARCHAR(255) NOT NULL,
    numero INTEGER NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE
);

-- =====================================================
-- USUARIOS
-- =====================================================

CREATE TABLE DB_Usuario (
    DB_Usuario_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codUsuario INTEGER NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    DB_Rol_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_Usuario_Rol
        FOREIGN KEY (DB_Rol_ID)
        REFERENCES DB_Rol(DB_Rol_ID)
);

CREATE TABLE DB_PermisoUsuario (
    DB_Permiso_ID INTEGER NOT NULL,
    DB_Usuario_ID INTEGER NOT NULL,

    PRIMARY KEY (DB_Permiso_ID, DB_Usuario_ID),

    CONSTRAINT FK_PermisoUsuario_Permiso
        FOREIGN KEY (DB_Permiso_ID)
        REFERENCES DB_Permiso(DB_Permiso_ID),

    CONSTRAINT FK_PermisoUsuario_Usuario
        FOREIGN KEY (DB_Usuario_ID)
        REFERENCES DB_Usuario(DB_Usuario_ID)
);

-- =====================================================
-- INVENTARIO
-- =====================================================

CREATE TABLE DB_Lote (
    DB_Lote_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codLote VARCHAR(255) NOT NULL,
    nombreProducto VARCHAR(255) NOT NULL,
    DB_Proveedor_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_Lote_Proveedor
        FOREIGN KEY (DB_Proveedor_ID)
        REFERENCES DB_Proveedor(DB_Proveedor_ID)
);

CREATE TABLE DB_Insumo (
    DB_Insumo_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codInsumo VARCHAR(255) NOT NULL,
    stock DOUBLE PRECISION NOT NULL,
    DB_Lote_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_Insumo_Lote
        FOREIGN KEY (DB_Lote_ID)
        REFERENCES DB_Lote(DB_Lote_ID)
);

-- =====================================================
-- PLATOS
-- =====================================================

CREATE TABLE DB_Plato (
    DB_Plato_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codPlato VARCHAR(255) NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    precio DOUBLE PRECISION NOT NULL,
    imagenUrl VARCHAR(255) NOT NULL,
    disponible BOOLEAN NOT NULL DEFAULT TRUE,
    DB_Categoria_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_Plato_Categoria
        FOREIGN KEY (DB_Categoria_ID)
        REFERENCES DB_Categoria(DB_Categoria_ID)
);

CREATE TABLE DB_InsumoPlato (
    DB_Plato_ID INTEGER NOT NULL,
    DB_Insumo_ID INTEGER NOT NULL,

    codPlato VARCHAR(255) NOT NULL,
    idInsumo INTEGER NOT NULL,
    cantidad DOUBLE PRECISION NOT NULL,
    esOpcional BOOLEAN NOT NULL DEFAULT FALSE,

    PRIMARY KEY (DB_Plato_ID, DB_Insumo_ID),

    CONSTRAINT FK_DB_InsumoPlato_Plato
        FOREIGN KEY (DB_Plato_ID)
        REFERENCES DB_Plato(DB_Plato_ID),

    CONSTRAINT FK_DB_InsumoPlato_Insumo
        FOREIGN KEY (DB_Insumo_ID)
        REFERENCES DB_Insumo(DB_Insumo_ID)
);

-- =====================================================
-- PEDIDOS
-- =====================================================

CREATE TABLE DB_Pedido (
    DB_Pedido_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codPedido INTEGER NOT NULL,
    fecha DATE NOT NULL,
    total DOUBLE PRECISION NOT NULL,
    estado VARCHAR(255) NOT NULL,
    observacion VARCHAR(255) NOT NULL,

    DB_Mesa_ID INTEGER NOT NULL,
    DB_Usuario_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_Pedido_Mesa
        FOREIGN KEY (DB_Mesa_ID)
        REFERENCES DB_Mesa(DB_Mesa_ID),

    CONSTRAINT FK_DB_Pedido_Usuario
        FOREIGN KEY (DB_Usuario_ID)
        REFERENCES DB_Usuario(DB_Usuario_ID)
);

CREATE TABLE DB_PlatoPedido (
    DB_PlatoPedido_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codPlatoPedido INTEGER NOT NULL,
    precioUnitario DOUBLE PRECISION NOT NULL,
    estado VARCHAR(255) NOT NULL,

    DB_Pedido_ID INTEGER NOT NULL,
    DB_Plato_ID INTEGER NOT NULL,

    CONSTRAINT FK_DB_PlatoPedido_Pedido
        FOREIGN KEY (DB_Pedido_ID)
        REFERENCES DB_Pedido(DB_Pedido_ID),

    CONSTRAINT FK_DB_PlatoPedido_Plato
        FOREIGN KEY (DB_Plato_ID)
        REFERENCES DB_Plato(DB_Plato_ID)
);

-- =====================================================
-- FACTURACI�N
-- =====================================================

CREATE TABLE DB_Factura (
    DB_Factura_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    serie VARCHAR(255) NOT NULL,
    numero INTEGER NOT NULL,
    fecha DATE NOT NULL,

    subtotal NUMERIC(10,2) NOT NULL,
    igv NUMERIC(10,2) NOT NULL,
    total NUMERIC(10,2) NOT NULL,

    DB_Pedido_ID INTEGER NOT NULL UNIQUE,

    CONSTRAINT FK_DB_Factura_Pedido
        FOREIGN KEY (DB_Pedido_ID)
        REFERENCES DB_Pedido(DB_Pedido_ID)
);

-- =====================================================
-- �NDICES OPCIONALES
-- =====================================================

CREATE INDEX IDX_USUARIO_EMAIL
    ON DB_Usuario(email);

CREATE INDEX IDX_PEDIDO_FECHA
    ON DB_Pedido(fecha);

CREATE INDEX IDX_FACTURA_NUMERO
    ON DB_Factura(numero);

CREATE INDEX IDX_PLATO_NOMBRE
    ON DB_Plato(nombre);